language:
  - python

python:
  - '3.6'

install:
  - pip install  -r requirements.txt

script:
  - nosetests
  - nosetests --with-coverage --cover-package=app

on_success: change
after_success: coveralls
on_failure: always